import type { Metadata } from "next";
import { Geist, Geist_Mono,Google_Sans } from "next/font/google";
import "./globals.css";
import { TransitionProvider } from "@/context/TransitionContext";
import TransitionOverlay from "../animates/TransitionOverlay";
import LayoutContent from "../animates/LayoutContent";

// import Transition from "./Components/common/Transition"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const Sans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${Sans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Transition />
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";



export default function RootLayout({ children }) {
  return (
    <html lang="en"
     
      className={`${geistSans.variable} ${Sans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        <TransitionProvider>
          <LayoutContent>
            {children}
          </LayoutContent>
        </TransitionProvider>
      </body>
    </html>
  );
}
